export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TASKS_REPOSITORY = 'TASKS_REPOSITORY';
export const RANKS_REPOSITORY = 'RANKS_REPOSITORY';
export const LANGUAGES_REPOSITORY = 'LANGUAGES_REPOSITORY';
export const SOLVED_TASKS_REPOSITORY = 'SOLVED_TASKS_REPOSITORY';
export const USER_STATUSES_REPOSITORY = 'USER_STATUSES_REPOSITORY';
export const TESTS_REPOSITORY = 'TESTS_REPOSITORY';
export const FAVOURITE_TASKS_REPOSITORY = 'FAVOURITE_TASKS_REPOSITORY';
